name       : rofi
version    : 1.5.4
release    : 13
source     :
    - https://github.com/davatorium/rofi/releases/download/1.5.4/rofi-1.5.4.tar.xz : 91a502cc29f964b529cd6228dbe655e82ab4e69c9852d23a24d9c1efb1af54db
license    : MIT
component  : system.utils
summary    : A window switcher, run dialog and dmenu replacement
description: |
    Rofi started as clone of simpleswitcher, written by Sean Pringle a popup window switcher roughly based on superswitcher. Simpleswitcher laid the foundations and therefor Sean Pringle deserves most of the credit for this tool. Rofi, renamed as it lost the simple property, has been extended with extra features, like a run-dialog, ssh-launcher and can act as a drop-in dmenu replacement, making it a very versatile tool.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(pango)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xkbcommon)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
