name       : rofi
version    : 1.3.1
release    : 3
source     :
    - https://github.com/DaveDavenport/rofi/releases/download/1.3.1/rofi-1.3.1.tar.xz : b52cf1170f5c7c38f6399ee44f23ebbd87ac349d6a34f32f5d169966765c87e8
license    : MIT
component  : system.utils
summary    : A window switcher, run dialog and dmenu replacement
description: |
    Rofi started as clone of simpleswitcher, written by Sean Pringle a popup window switcher roughly based on superswitcher. Simpleswitcher laid the foundations and therefor Sean Pringle deserves most of the credit for this tool. Rofi, renamed as it lost the simple property, has been extended with extra features, like a run-dialog, ssh-launcher and can act as a drop-in dmenu replacement, making it a very versatile tool.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(glib-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pango)
    - pkgconfig(xcb)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xkbcommon)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
